# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-24 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='note_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='created_on',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='updated_on',
            new_name='edited',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='note_title',
            new_name='title',
        ),
    ]
