# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-21 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191121_1420'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notes',
            new_name='Note',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
