# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-24 10:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20191121_1505'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
