# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-24 11:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='note_uid',
        ),
        migrations.AlterField(
            model_name='note',
            name='username',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
