# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-24 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20191124_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='username',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
